### ISSUE TITLE
如何编译第9章的示例？

### ISSUE THREAD

**Issue by yinhaibo** [chansonZ/Understanding-the-Net-SNMP#1]
在按书籍中的方法，把ch9的目录复制到net-snmp-5.7.3源码目录下，并使用configure.txt的文件执行命令，出现错误：

```
checking for uname... /bin/uname
checking whether the Perl function system() invokes a POSIX shell... yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/zabbix/net-snmp-5.7.3':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

另外，对于app如何编译，书中描述的不是很清楚？
还请张老师多多指教。

**Comment by yinhaibo** [comment]
经过一天的折腾，编译通过了，该问题也解决了。编译的Makefile文件如下（简要写的）

```
OBJS=snmpipc.o app.o

all:app


app:app.o libsnmpipc.so
        gcc -fPIC -rdynamic -L./ -lsnmpipc -o app app.o


libsnmpipc.so:snmpipc.o
        gcc -shared -fPIC -rdynamic -o libsnmpipc.so snmpipc.o

$(OBJS):%.o:%.c
        gcc -c -fPIC -o $@ $^


clean:
        rm *.o
        rm libsnmpipc.so
        rm app
```

出现该问题的原因就是configure在使用示例中的配置文件脚本配置是指定了-lsnmpipc，要求编译libsnmpipc.so文件，在configure配置的时候会测试编译器是否正常，而且会使用上面的参数，所以在库文件找不到的前提下，提示编译器错误。

上述编译文件使用但当前目录的libsnmpipc.so文件编译，如果需要测试运行，需要指定运行目录：

```
export LD_LIBRARY_PATH=./
```

为了保证snmp可以配置通过，最后需**要把libsnmpipc.so文件复制到/usr/lib64/目录下**, 如果已经复制该文文件到/usr/lib64目录下面，还需要调试该文件时，需要把系统目录的文件删除，不然会优先系统目录下的动态库文件。

另外，在代码snmpipc.c文件的235行( https://github.com/chansonZ/Understanding-the-Net-SNMP/blob/master/ch9/snmpipc.c#235 )在64位环境下会出现问题，导致段错误。

**Comment by charles-shh** [comment]
还需要调试该文件时，需要把系统目录的文件删除，不然会优先系统目录下的动态库文件。？？？删除什么文件
