### ISSUE TITLE
python Net-SNMP开发环境搭建

### ISSUE THREAD

**Issue by 315xiaoyao** [chansonZ/Understanding-the-Net-SNMP#2]
你好作者可否出一个环境搭建的教程啊。折腾了好久都没有成功。
需求：
1、windows 10 + python3.7 需要如何来安装相关环境
2、Centos7 +python3.7 环境搭建（目前搭建成功，但是在这里面写代码效果不太好）
希望作者能为我们这些小白用户多考虑一下，谢谢！

**Comment by chansonZ** [comment]
@315xiaoyao 读者你好！

1、不好意思，我没有在Windows环境下开发并运行于Windows环境下Net-SNMP的经历
2、书中所有的例子/程序都在Linux环境下运行。其中你提到的Python环境，是有相关依赖的，所以建议在Linux环境下进行

至于代码编写，程序的开发环境，与运行环境无关。一般在Window环境下开发，调试和运行在Linux.
比如，我个人几乎都在Windows环境下编写代码，比如Notepad++,Sublime,sourse insight.然后将其上传到Linux环境下调试和运行（ftp或共享环境等）
另外，个人或企业开发Net-SNMP一般运行于ARM板等嵌入式环境，所以开发环境是交叉编译环境，这些环境的搭建还涉及目标机的环境，建议在公司内或网上寻求帮助，很容易解决。
