### ISSUE TITLE
centos7当中编译安装net-snmp

### ISSUE THREAD

**Issue by 315xiaoyao** [chansonZ/Understanding-the-Net-SNMP#3]
希望作者可以出一个详细的Centos7当中安装net-snmp的教程。我这边后期是想用python来进行开发。谢谢！

**Comment by chansonZ** [comment]
7.1	系统搭建

有详细的介绍，源码下载后，配置编译即可：

比如：

./configure --with-openssl=internal -with-default-snmp-version="3" --with-sys-contact="xtdwxk@gmail.com" --with-sys-location="shenzhenNS" --with-logfile=/var/log/snmpd.log --with-persistent-directory=/var/net-snmp


如果不想做开发，直接yum install 就好
